### ISSUE TITLE
Create a RESTful API using Apiary. Log into Apiary with your GitHub credentials and connect Apiary to your repos.

### ISSUE THREAD

**Issue by jabrouwer82** [plberg/cs373-idb#13]
Think carefully about the types and format of the requests and responses.

**Comment by jabrouwer82** [comment]
Parker, you need to click on the little settings box at the top of the api editor and then scroll to the bottom and sync it to this github so we can have the apib file in the repo. I think only you, as the owner of the api, can do this.

**Comment by plberg** [comment]
Added an apib manually for now, remind me to try to set up constant syncing with github later.

http://docs.celebrityrapsheet.apiary.io/#
