### ISSUE TITLE
Add twitter feeds to celebrity pages

### ISSUE THREAD

**Issue by jabrouwer82** [plberg/cs373-idb#31]
We have all their twitter handles, they just need to be plugged into some html/javascript like so: https://dev.twitter.com/web/embedded-timelines#user.

**Comment by jabrouwer82** [comment]
Also add some to crimes, just by searching for the crime. Maybe on charges too, by searching for the celebrity/crime.

**Comment by i-daszkowski** [comment]
We need to fix the implementation because right now every celebrities' twitter feed is Robert Downey Jr.'s.

**Comment by jabrouwer82** [comment]
Sorry, I thought I commented on this. Twitter doesn't allow for dynamically generated embedded feeds, so we tossed this idea, I'll link the commit/issue in a bit
