### ISSUE TITLE
Make the tests runnable by the graders

### ISSUE THREAD

**Issue by phtimmins** [plberg/cs373-idb#40]
per https://piazza.com/class/i563clif2i169a?cid=246 we don't need a tests page, but we do need some way for the graders to run the tests

**Comment by jabrouwer82** [comment]
Ugh, can our tests run on the cs machines?

**Comment by phtimmins** [comment]
Could do that, though I don't know how to setup the environment so they can run them. Would it make sense to provide them with a password login to the rackspace machine?

**Comment by jabrouwer82** [comment]
So I take it the tests won't work independent of our postgres dB? I suppose I could set up some kind of password login for the graders

**Comment by phtimmins** [comment]
Yeah, and with the dependancies on libpq-dev, etc..., I think a password is the easiest solution. We can write how to acess it in the notes on the google doc

**Comment by jabrouwer82** [comment]
I'm just going to enble password login for now and give the graders the postgres user to log in as
