### ISSUE TITLE
Create a Github Wiki

### ISSUE THREAD

**Issue by i-daszkowski** [plberg/cs373-idb#43]
Improve the technical report.
Convert the document to a GitHub Wiki.
For this phase make it at least 15 pages.
Assume 250 words per page, so 3,750 words.
The audience comprises other software developers, as opposed to users.
Document the RESTful API and the PostgreSQL DB well.
Format the report clearly, attractively, and consistently, using good headers, figures, and grammar.

**Comment by jabrouwer82** [comment]
This is effectively done.

See also #70
