### ISSUE TITLE
Fix the API based on grader's notes.

### ISSUE THREAD

**Issue by i-daszkowski** [plberg/cs373-idb#46]
Fix the API and make sure to adapt the Flask models accordingly.

**Comment by jabrouwer82** [comment]
Our notes:
Please write the RESTful API section.
The introduction has good formatting, please s=consider changing everything else to be consistant with it.

**Comment by jabrouwer82** [comment]
Sorry, I misread the original issue, I thought this was another one discussing the report. We had no feedback on the API, so I'll close this.
