### ISSUE TITLE
Unit Tests

### ISSUE THREAD

**Issue by i-daszkowski** [plberg/cs373-idb#48]
Create a way to run all of the unit tests through the webpage.

**Comment by plberg** [comment]
Create a set of unit tests to test the RESTful API and the underlying PostgreSQL DB.

**Comment by jabrouwer82** [comment]
I think Parker is working on getting a flask server running for the test server. In the mean-time, I'll look into configuring our nginx server to server to both servers.

**Comment by phtimmins** [comment]
There is now a working test server, and a page on the site that queries the server and prints its output. The test page gets the url of the test server api from environment variable: 'TEST_API_URL' though it currently defaults to 'http://23.253.252.30:8989/api/tests'

**Comment by plberg** [comment]
Game, set, match.
