### ISSUE TITLE
Add police line image to splash page

### ISSUE THREAD

**Issue by plberg** [plberg/cs373-idb#56]
This may require some gimp / photoshop magic.

Subissue of #53

**Comment by jabrouwer82** [comment]
Some large images I found for a splash image:
https://lifeandothertales.files.wordpress.com/2012/12/police-line-do-not-cross-tape-at-crime-scene-1-2000x1349.jpg
http://nationaltoolkit.csw.fsu.edu/wp-content/uploads/2012/09/Policelinetape.jpg
http://www.hdwallbackgrounds.com/wp-content/uploads/2014/06/Police-Line-Crime-Scene-Wallpaper-Image-HD.jpeg
http://www.portlandoccupier.org/wp-content/uploads/2011/11/Police-Line.jpg  (I like this one)
Heres the search I used to find them:
https://www.google.com/search?q=police+line&client=ubuntu&channel=fs&biw=1920&bih=1036&source=lnms&tbm=isch&sa=X&ei=ByckVbSPPMLosAWloIGoBg&ved=0CAYQ_AUoAQ#channel=fs&tbs=isz:lt%2Cislt:xga&tbm=isch&q=police+line&imgdii=_

**Comment by jabrouwer82** [comment]
See 3ebdcecebe0a4ab0b1d8dab74986262001adeed2 for the vector resources I added.

**Comment by plberg** [comment]
Won't get done before this deadline - closing for now.
