### ISSUE TITLE
Technical report needs ~1000 more words

### ISSUE THREAD

**Issue by jabrouwer82** [plberg/cs373-idb#70]
Our current google doc has 2705 words.  If you edit the wiki by adding words, please update the count here so we don't need to tally it constantly.

We need 3750 words or so.

**Comment by jabrouwer82** [comment]
Sub issue of #64 and #61

**Comment by i-daszkowski** [comment]
Added a Design subsection under RESTful API with 189 words. The new current total is now 2894 words, assuming all the content from the Google doc, bar the API pictures, has been added to the wiki.

**Comment by i-daszkowski** [comment]
Added a description of the "problem" that we tackled. The new current total is 3057 words. Do I get a cookie for breaking 3000 words?

**Comment by i-daszkowski** [comment]
Added reasoning behind the attributes we chose for each of the Models. New word count is 3255.

**Comment by jabrouwer82** [comment]
After a quick recount, it seems we only have 3054 words. I think I made an error in the initial count.

**Comment by phtimmins** [comment]
Got it up to 3200, just 500 needed

**Comment by jabrouwer82** [comment]
A ton of the design section needs to be rewritten when I finally get the test server running, so that will hopefully add some.

**Comment by plberg** [comment]
Exceeds required word count, closing.
